"""Service for generating PDF postmortem reports from incident analysis results."""

import os
from datetime import datetime
from fpdf import FPDF
from app.config import settings

class ReportService:
    """Generates professional PDF postmortem reports."""

    @staticmethod
    def _sanitize_text(text: str) -> str:
        """Replace Unicode characters unsupported by FPDF Latin-1 fonts."""
        replacements = {
            '\u2018': "'", '\u2019': "'",  # smart single quotes
            '\u201c': '"', '\u201d': '"',  # smart double quotes
            '\u2013': '-', '\u2014': '--', # en/em dashes
            '\u2026': '...', '\u2022': '*',# ellipsis, bullet
            '\u00a0': ' ',                  # non-breaking space
            '\u200b': '',                   # zero-width space
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        # Final fallback: encode to latin-1, replacing unknown chars
        return text.encode('latin-1', errors='replace').decode('latin-1')

    def generate_postmortem(self, analysis_result: dict, filename: str = None) -> str:
        """Create a PDF report from analysis results."""
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"postmortem_{timestamp}.pdf"

        # Ensure directory exists
        report_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data", "reports")
        os.makedirs(report_dir, exist_ok=True)
        report_path = os.path.join(report_dir, filename)

        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 24)
        pdf.set_text_color(33, 118, 210)  # Primary Blue
        pdf.cell(0, 20, "Incident Postmortem Report", ln=True, align="C")
        
        pdf.set_font("Arial", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"Generated by {settings.APP_NAME} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        pdf.ln(10)

        # Basic Info
        pdf.set_font("Arial", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "1. Executive Summary", ln=True)
        pdf.set_font("Arial", "", 12)
        pdf.multi_cell(0, 8, f"Issue: {self._sanitize_text(analysis_result.get('detected_issue', 'Unknown'))}")
        pdf.multi_cell(0, 8, f"Severity: {analysis_result.get('severity', 'Medium').upper()}")
        pdf.multi_cell(0, 8, f"Status: Resolved")
        pdf.ln(5)

        # Root Cause
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "2. Root Cause Analysis", ln=True)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, self._sanitize_text(analysis_result.get("root_cause", "No root cause identified.")))
        pdf.ln(5)

        # Evidence
        evidence = analysis_result.get("evidence", [])
        if evidence:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "3. Supporting Evidence", ln=True)
            pdf.set_font("Arial", "", 10)
            for item in evidence:
                pdf.multi_cell(0, 6, f"- {self._sanitize_text(item)}")
            pdf.ln(5)

        # Fix Steps
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "4. Remediation Steps", ln=True)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, self._sanitize_text(analysis_result.get("suggested_fix", "No fix identified.")))
        pdf.ln(5)

        # Code Fix (if any)
        code = analysis_result.get("improved_code", "")
        if code:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "5. Code Improvement", ln=True)
            pdf.set_font("Courier", "", 9)
            pdf.set_fill_color(240, 240, 240)
            pdf.multi_cell(0, 5, self._sanitize_text(code), fill=True)
            pdf.ln(5)

        # Prevention
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "6. Preventive Measures", ln=True)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, self._sanitize_text(analysis_result.get("preventive_measures", "No preventive measures listed.")))
        
        pdf.output(report_path)
        return report_path

report_service = ReportService()
